"""Emit deterministic Opentrons API v2 (OT-2) Python from a ``TransferGraph``.

Strategy
--------
We emit *explicit* ``pick_up_tip`` / ``aspirate`` / ``dispense`` / ``drop_tip`` calls rather
than the ``transfer()`` convenience method, because tip lifetime is the thing we optimize and
we need full control over it. This keeps the mapping IR -> code direct and auditable.

Tip lifetime rules, walking transfers in order:

* A transfer with ``tip_group = g`` shares one tip with all other ``tip_group = g`` transfers.
  The tip is picked up at the first transfer of the group and dropped after the last.
* A transfer with ``channel_group = c`` is one row of an 8-channel move: the multi pipette
  addresses the column via its top well; the 8 aligned single transfers collapse into one
  aspirate/dispense pair. One tip (well: 8 physical tips) per channel group.
* An ungrouped transfer gets its own tip: pick up, aspirate, dispense, drop.

Multi-channel packing: a channel group is emitted as a single aspirate from the group's source
column top-well and a single dispense into the dest column top-well. The grouping pass
guarantees all 8 rows share source/dest columns and volume.
"""

from __future__ import annotations

from pipettec.ir import TransferGraph

_HEADER = '''"""Generated by PipetteC (github: pipettec). Do not edit by hand.

{title}
"""

from opentrons import protocol_api

metadata = {metadata!r}
requirements = {{"robotType": "OT-2", "apiLevel": "{api_level}"}}


def run(protocol: protocol_api.ProtocolContext) -> None:
'''


def _pyname(prefix: str, ident: str) -> str:
    safe = "".join(ch if ch.isalnum() else "_" for ch in ident)
    return f"{prefix}_{safe}"


def generate(graph: TransferGraph) -> str:
    """Return a complete, deterministic Opentrons OT-2 protocol module as a string."""
    api_level = graph.metadata.get("apiLevel", "2.15")
    title = graph.metadata.get("name", "PipetteC protocol")
    meta = {
        "protocolName": graph.metadata.get("name", "PipetteC protocol"),
        "author": graph.metadata.get("author", "PipetteC"),
        "description": graph.metadata.get("description", "Generated liquid-handling protocol."),
    }
    lines: list[str] = []
    lines.append(_HEADER.format(title=title, metadata=meta, api_level=api_level))

    body: list[str] = []
    lw_var: dict[str, str] = {}
    for lw in graph.labware:
        var = _pyname("lw", lw.id)
        lw_var[lw.id] = var
        body.append(f'{var} = protocol.load_labware("{lw.load_name}", "{lw.slot}")')

    # Only load instruments actually used by a transfer, so codegen never emits a dead pipette
    # (which the simulator warns about and which reads as sloppy generated code).
    used_instruments = {t.instrument for t in graph.transfers}
    inst_var: dict[str, str] = {}
    for inst in graph.instruments:
        if inst.id not in used_instruments:
            continue
        var = _pyname("pip", inst.id)
        inst_var[inst.id] = var
        racks = ", ".join(lw_var[r] for r in inst.tip_racks)
        body.append(
            f'{var} = protocol.load_instrument("{inst.model}", "{inst.mount}", '
            f"tip_racks=[{racks}])"
        )

    body.append("")
    body += _emit_transfers(graph, lw_var, inst_var)

    lines.append("\n".join("    " + b if b else "" for b in body))
    lines.append("")
    return "\n".join(lines)


def _well_ref(lw_var: dict[str, str], target: str) -> str:
    lid, well = target.split(":", 1)
    return f'{lw_var[lid]}["{well}"]'


def _emit_transfers(
    graph: TransferGraph, lw_var: dict[str, str], inst_var: dict[str, str]
) -> list[str]:
    body: list[str] = []
    # Precompute, per tip_group, the index of its first and last transfer so we know when to
    # pick up / drop. Channel groups are single logical ops, so they pick up and drop inline.
    first_of_group: dict[int, int] = {}
    last_of_group: dict[int, int] = {}
    for i, t in enumerate(graph.transfers):
        if t.tip_group is not None:
            first_of_group.setdefault(t.tip_group, i)
            last_of_group[t.tip_group] = i

    emitted_channel_groups: set[int] = set()

    for i, t in enumerate(graph.transfers):
        pip = inst_var[t.instrument]
        if t.channel_group is not None:
            if t.channel_group in emitted_channel_groups:
                continue
            emitted_channel_groups.add(t.channel_group)
            body += _emit_channel_group(graph, lw_var, pip, t.channel_group)
            continue

        src = _well_ref(lw_var, t.source)
        dst = _well_ref(lw_var, t.dest)
        vol = _fmt_vol(t.volume)

        if t.tip_group is not None:
            if first_of_group[t.tip_group] == i:
                body.append(f"{pip}.pick_up_tip()")
            body.append(f"{pip}.aspirate({vol}, {src})")
            body.append(f"{pip}.dispense({vol}, {dst})")
            if last_of_group[t.tip_group] == i:
                body.append(f"{pip}.drop_tip()")
        else:
            body.append(f"{pip}.pick_up_tip()")
            body.append(f"{pip}.aspirate({vol}, {src})")
            body.append(f"{pip}.dispense({vol}, {dst})")
            body.append(f"{pip}.drop_tip()")
    return body


def _emit_channel_group(
    graph: TransferGraph, lw_var: dict[str, str], pip: str, group: int
) -> list[str]:
    members = [t for t in graph.transfers if t.channel_group == group]
    rep = members[0]
    # A multi-channel move is addressed by the column's top well (row A).
    src = _well_ref(lw_var, f"{rep.source_labware}:A{rep.source_well[1:]}")
    dst = _well_ref(lw_var, f"{rep.dest_labware}:A{rep.dest_well[1:]}")
    vol = _fmt_vol(rep.volume)
    return [
        f"{pip}.pick_up_tip()",
        f"{pip}.aspirate({vol}, {src})",
        f"{pip}.dispense({vol}, {dst})",
        f"{pip}.drop_tip()",
    ]


def _fmt_vol(v: float) -> str:
    if abs(v - round(v)) < 1e-9:
        return str(int(round(v)))
    return repr(round(v, 3))
