"""Generated by PipetteC (github: pipettec). Do not edit by hand.

cherry_pick
"""

from opentrons import protocol_api

metadata = {'protocolName': 'cherry_pick', 'author': 'PipetteC', 'description': 'Cherry-pick / hit-pick arbitrary transfers'}
requirements = {"robotType": "OT-2", "apiLevel": "2.15"}


def run(protocol: protocol_api.ProtocolContext) -> None:

    lw_src = protocol.load_labware("corning_96_wellplate_360ul_flat", "1")
    lw_dst = protocol.load_labware("corning_96_wellplate_360ul_flat", "2")
    lw_tips = protocol.load_labware("opentrons_96_tiprack_300ul", "3")
    lw_tips2 = protocol.load_labware("opentrons_96_tiprack_300ul", "6")
    pip_p300 = protocol.load_instrument("p300_single_gen2", "right", tip_racks=[lw_tips, lw_tips2])

    pip_p300.pick_up_tip()
    pip_p300.aspirate(30, lw_src["A1"])
    pip_p300.dispense(30, lw_dst["A1"])
    pip_p300.aspirate(20, lw_src["A1"])
    pip_p300.dispense(20, lw_dst["E1"])
    pip_p300.drop_tip()
    pip_p300.pick_up_tip()
    pip_p300.aspirate(30, lw_src["C4"])
    pip_p300.dispense(30, lw_dst["B1"])
    pip_p300.drop_tip()
    pip_p300.pick_up_tip()
    pip_p300.aspirate(50, lw_src["H12"])
    pip_p300.dispense(50, lw_dst["C1"])
    pip_p300.drop_tip()
    pip_p300.pick_up_tip()
    pip_p300.aspirate(25, lw_src["E7"])
    pip_p300.dispense(25, lw_dst["D1"])
    pip_p300.drop_tip()
