"""Generated by PipetteC (github: pipettec). Do not edit by hand.

plate_normalization
"""

from opentrons import protocol_api

metadata = {'protocolName': 'plate_normalization', 'author': 'PipetteC', 'description': 'Normalize wells to a common volume with diluent'}
requirements = {"robotType": "OT-2", "apiLevel": "2.15"}


def run(protocol: protocol_api.ProtocolContext) -> None:

    lw_plate = protocol.load_labware("corning_96_wellplate_360ul_flat", "1")
    lw_reagents = protocol.load_labware("nest_12_reservoir_15ml", "2")
    lw_tips = protocol.load_labware("opentrons_96_tiprack_300ul", "3")
    lw_tips2 = protocol.load_labware("opentrons_96_tiprack_300ul", "6")
    pip_p300 = protocol.load_instrument("p300_single_gen2", "right", tip_racks=[lw_tips, lw_tips2])

    pip_p300.pick_up_tip()
    pip_p300.aspirate(80, lw_reagents["A1"])
    pip_p300.dispense(80, lw_plate["A1"])
    pip_p300.aspirate(120, lw_reagents["A1"])
    pip_p300.dispense(120, lw_plate["B1"])
    pip_p300.aspirate(50, lw_reagents["A1"])
    pip_p300.dispense(50, lw_plate["C1"])
    pip_p300.aspirate(140, lw_reagents["A1"])
    pip_p300.dispense(140, lw_plate["D1"])
    pip_p300.aspirate(100, lw_reagents["A1"])
    pip_p300.dispense(100, lw_plate["A2"])
    pip_p300.aspirate(60, lw_reagents["A1"])
    pip_p300.dispense(60, lw_plate["B2"])
    pip_p300.aspirate(110, lw_reagents["A1"])
    pip_p300.dispense(110, lw_plate["C2"])
    pip_p300.aspirate(90, lw_reagents["A1"])
    pip_p300.dispense(90, lw_plate["D2"])
    pip_p300.drop_tip()
